### ISSUE TITLE
Feature - Search

### ISSUE THREAD

**Issue by Ragnar-Hardarson** [veritus/veritus-web#38]
# Description
People come to our site for a specific reason.

If we manage to create the perfect overview on the site, everybody will instantly see exactly what they were looking for when they open our site.

This is however never the case if you're presenting a lot of data 😔

This calls for a search feature.

# Todos
- [ ] Research search solutions out there
- [ ] List solutions with pros/cons
- [ ] POC (1st PR)
- [ ] Full release (2nd PR)

**Comment by Ragnar-Hardarson** [comment]
Some candidates to consider:

## Haystack + Elasticsearch
Specifically [Django-haystack](https://django-haystack.readthedocs.io/en/master/)

#### Pros
@AriHrannar has set this up in another project

#### Cons
- Takes time to implement
- Need to host ourselves (Adds to hosting load + DevOps work)

## Algolia
[Algolia](https://www.algolia.com/ref/docsearch?utm_source=docsearch&utm_medium=link&utm_term=footer&utm_campaign=flow.org)

#### Pros
- Algolia takes care of hosting

#### Cons
- Not free*

_*Free tier should suffice. Starter tier is really cheap_

**Comment by Ragnar-Hardarson** [comment]
*Algolia in action on [Flow documentation site](https://flow.org/en/docs/)*

![searching](https://user-images.githubusercontent.com/22854722/27001735-4d99f5ca-4dd1-11e7-8ec6-7db543ee1a9c.gif)

**Comment by Ragnar-Hardarson** [comment]
I first saw Algolia featured in this blog post https://hackernoon.com/from-idea-to-4m-page-views-in-4-weeks-622aa194787d

**Comment by AriHrannar** [comment]
Algolia does look pretty cool. They even say that they can increase the free limits for open source.

Only issue that I see with it is that it would suck to switch when we hit the limits. $600 a year is pretty steep.

Like they say the limit is 10.000 records. We would have to allow searching for both cases and promises at least. 

If we just look at the promises
There are 6 districts and 7 parties. If each party has 10 candidates in each district we have 6*7*10 = 420 possible politicians. If each makes 10 promises, we are already at 4200 records.

So it feels like we would reach the limit relatively soon :(

**Comment by Ragnar-Hardarson** [comment]
Good to keep the limits in mind like that.
I'd like to revisit this issue when we actually have something to display
(and something to display that data with 😅)

An exhaustive list of search engines should definitely contain more than
only these two options.
